name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Make sure to use the version compatible with your Angular app

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build -- --configuration production --base-href "https://www.timezones.ai/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/<your-app-name>  # Replace <your-app-name> with the correct folder name in dist
